library(readr)
library(dplyr)
library(ggplot2)
cars <- read.csv("E:/Datasets/Linear-Regression-master/cars.csv")
View(cars)
head(cars)
tail(cars)
nrow(cars)
ncol(cars)

names(cars)
summary(cars)
is.na(cars)
is.na(cars$speed)
is.na(cars$dist)
plot(cars$speed)
plot(cars$dist,col= "red")
plot(cars$dis,cars$speed,col=5)
boxplot(cars$speed)
boxplot(cars$dist)
boxplot(cars,col=3)
fit <- lm(speed~dist,cars)
summary(fit)
abline(fit)
par(mfrow=c(2,2))
plot((fit))
